public class Calculate
{
    public integer number1{get;set;}
 
    public integer number2 {get;set;}
    
    public integer add(){
        return(number1 + number2);
    }
    
    public integer substract(){
        return(number1 - number2);
    }
    
    public integer multiply(){
        return(number1 * number2);
    }
    
    public integer divide(){
        return(number1 / number2);
    }
    
}